language: node_js
node_js:
 - "0.10"
before_script:
 - npm install -g grunt-cli
 - ./bin/sauce-connect-setup.sh
after_success: ./bin/update-gh-pages.sh
env:
  global:
    # GH pages
    - GH_REF: github.com/claudijo/storage-messenger.git
    - secure: MfG10xN5RPxn+K8ic3+8qsJFI6qJS5Xo4KgYsGiOK1d4fjnV9gcxuz/EdW/FnaRbsZyAs8MqpYTIRvR+nOf4TDErIi5e6WkAEjTfGWG9ViNdShPuZI5epy3Rdn+CTvj0qa0bKG9bMCYSgdNHhPgjY2mXv+YknacYvCHadP/SrW0=
    # Sauce Labs
    - SAUCE_USERNAME: claudijo
    - secure: Za+/e0T5PJfvX3bj+MJ62OzJ6hJ6rmyl7he16UhLeoiOJ3C/6F+Xcyqdpk5NoxpW+hrjEi5ZD+6RvZ5FlN0tWcv6nlZW3vIgp4HxFhGZyBPfWXZ8PXf2xl/c3sk7/495GQrv0qmrp2BNiQllnAWsqGE4PZTs4gVxSEo79BS1NgA=
